import numpy as np
myarr= np.array([4,5,6,78,96])
leoe=np.array([[4,578,53,36]])
print(myarr[0:3])
print(type(myarr))
print(myarr)
print(leoe[0:3])
print(leoe[0:1,0:3])
print(type(leoe))
print(leoe)
print(leoe[0,3])
print(leoe.shape)
print(myarr.dtype)
print(leoe.dtype)
